// <auto-generated />
using DogHouse.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DogHouse.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241106211903_AddMoreData")]
    partial class AddMoreData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DogHouse.Domain.Entities.Dog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Colors")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("TailLength")
                        .HasColumnType("float");

                    b.Property<double>("Weight")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Dogs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Colors = "[\"Red\",\"Amber\"]",
                            Name = "Neo",
                            TailLength = 22.0,
                            Weight = 32.0
                        },
                        new
                        {
                            Id = 2,
                            Colors = "[\"Black\",\"White\"]",
                            Name = "Jessy",
                            TailLength = 7.0,
                            Weight = 30.0
                        },
                        new
                        {
                            Id = 3,
                            Colors = "[\"Brown\"]",
                            Name = "Max",
                            TailLength = 15.0,
                            Weight = 25.0
                        },
                        new
                        {
                            Id = 4,
                            Colors = "[\"Golden\"]",
                            Name = "Bella",
                            TailLength = 20.0,
                            Weight = 28.0
                        },
                        new
                        {
                            Id = 5,
                            Colors = "[\"Black\"]",
                            Name = "Charlie",
                            TailLength = 18.0,
                            Weight = 35.0
                        },
                        new
                        {
                            Id = 6,
                            Colors = "[\"White\"]",
                            Name = "Lucy",
                            TailLength = 10.0,
                            Weight = 22.0
                        },
                        new
                        {
                            Id = 7,
                            Colors = "[\"Gray\"]",
                            Name = "Cooper",
                            TailLength = 12.0,
                            Weight = 27.0
                        },
                        new
                        {
                            Id = 8,
                            Colors = "[\"Brown\",\"White\"]",
                            Name = "Daisy",
                            TailLength = 14.0,
                            Weight = 24.0
                        },
                        new
                        {
                            Id = 9,
                            Colors = "[\"Black\",\"Brown\"]",
                            Name = "Rocky",
                            TailLength = 16.0,
                            Weight = 29.0
                        },
                        new
                        {
                            Id = 10,
                            Colors = "[\"Golden\",\"White\"]",
                            Name = "Molly",
                            TailLength = 19.0,
                            Weight = 26.0
                        },
                        new
                        {
                            Id = 11,
                            Colors = "[\"Red\"]",
                            Name = "Buddy",
                            TailLength = 21.0,
                            Weight = 31.0
                        },
                        new
                        {
                            Id = 12,
                            Colors = "[\"Amber\"]",
                            Name = "Lola",
                            TailLength = 13.0,
                            Weight = 23.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
